//
// Created by tal on 10.12.2019.
//

#ifndef SIMULATOR_COMMANDS_DEFINEVARCOMMAND_H_
#define SIMULATOR_COMMANDS_DEFINEVARCOMMAND_H_

class DefineVarCommand {

};

#endif //SIMULATOR_COMMANDS_DEFINEVARCOMMAND_H_
