//
// Created by tal on 10.12.2019.
//

#ifndef SIMULATOR_COMMANDS_COMMENTCOMMAND_H_
#define SIMULATOR_COMMANDS_COMMENTCOMMAND_H_

class CommentCommand {

};

#endif //SIMULATOR_COMMANDS_COMMENTCOMMAND_H_
